### ISSUE TITLE
Script Breaks with DND Beyond Update + Multi-Classing

### ISSUE THREAD

**Issue by SupremeDevice** [donoftime/life-beyond#1]
First problem: DND Beyond seems to have changed `characterClass` to `charClass`, which although a simple change seems to cause the script to break, changing this fixes it.

Second problem: My character is a cleric who just multi-classed into Monk, and the script does not work and the console shows that subclassDefinition is null. However, loading up a copy that has the monk class removed causes the script to work again.

I realize it's probably not your intention to keep working on this, as it really is a feature that should be implemented by the actual staff, but I would appreciate it if you could somehow manage to fix this. In the meanwhile, I suppose I'll just patch the subclass check out on my end.

**Comment by donoftime** [comment]
Thank you for the report and PR @SupremeDevice! 

I will look into the changes this morning to see what is different after the update, and see about addressing the sub-classing issue with Monk 👀

**Comment by donoftime** [comment]
Version 1.0.1 is published to the Chrome Web Store now, and includes the change to fix this issue. For anyone who has the extension installed from the store, it should automatically update.
